### ISSUE TITLE
[Bug] [ColorIndicator] Plugin breaks user popout from mention

### ISSUE THREAD

**Issue by zerebos** [BinaryQuantumSoul/discord-better-messages#1]
With this plugin enabled, you can no longer click a user mention in chat to activate the user popout.

**Comment by BinaryQuantumSoul** [comment]
Noted. I think it's related to https://github.com/BinaryQuantumSoul/discord-better-messages/issues/3

**Comment by BinaryQuantumSoul** [comment]
Fixed in latest
