### ISSUE TITLE
[Feature Request] [ColorIndicator] Add wider support for colors

### ISSUE THREAD

**Issue by zerebos** [BinaryQuantumSoul/discord-better-messages#2]
It could be interesting to have this plugin support a wider array of valid css colors including different formats and perhaps even the named colors.

**Comment by BinaryQuantumSoul** [comment]
Done in latest version :D
![image](https://github.com/BinaryQuantumSoul/discord-better-messages/assets/19613657/7c0a9950-1059-4766-983f-9b8a553cf1ce)
