### ISSUE TITLE
[Idiocy] [ColorIndicator] My brain is failing to understand this

### ISSUE THREAD

**Issue by CropWasTaken** [BinaryQuantumSoul/discord-better-messages#4]
I'm definitely gonna feel stupid once this is answered but how do you actually make this plugin activate and recognize color codes, because for the life of me I can't seem to figure this one out. Sorry if this is wasting your time but I would like some help.

**Comment by BinaryQuantumSoul** [comment]
You need to have them inside code blocks.

So either `` `#00ff00` `` or `` ```color: red;``` `` should work

**Comment by BinaryQuantumSoul** [comment]
Though I detected a bug making the plugin sometimes not activating. The fix is in approval, so if above doesn't work just wait for the update

**Comment by CropWasTaken** [comment]
Whatever you applied to fix the plugin seems to be working, just downloaded the new version and stuff is working now. :D Thank you. Unsure of etiquette on Github when it comes to issue closes or whatever so I'll just let you close this.

**Comment by BinaryQuantumSoul** [comment]
You're welcome :)
