### ISSUE TITLE
No longer works.

### ISSUE THREAD

**Issue by wolframwinters** [BinaryQuantumSoul/discord-better-messages#7]
This nightmarish last update broke everything. 
![image](https://github.com/BinaryQuantumSoul/discord-better-messages/assets/173398889/b614fcb1-57b7-4ab2-a028-b498aa252541)

**Comment by BinaryQuantumSoul** [comment]
Hello, the fix is pushed but waiting for approval by plugin team. You can download latest version from this GitHub repo and make sure it is working.
