### ISSUE TITLE
[ColorIndicator] could not be compiled

### ISSUE THREAD

**Issue by FenekkuKitsune** [BinaryQuantumSoul/discord-better-messages#8]
TypeError: Cannot read properties of undefined (reading 'messageContent')
    at eval (betterdiscord://plugins/ColorIndicator.plugin.js:12:96)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)

**Comment by BinaryQuantumSoul** [comment]
I need context, are you using latest ?

**Comment by FenekkuKitsune** [comment]
Latest. It's suddenly and randomly decided to compile today, but it's not actually highlighting anything in the chat. I tried #fff and #ffffbb and neither were highlighted.

**Comment by BinaryQuantumSoul** [comment]
Can you try with this exact file ?
https://github.com/BinaryQuantumSoul/discord-better-messages/blob/main/plugins/ColorIndicator/ColorIndicator.plugin.js

I think you are not using the latest and I forgot to increase version number

**Comment by FenekkuKitsune** [comment]
I just tried it, and it doesn't work. It doesn't fail to compile as said, but it's not highlighting the text with the color.

**Comment by BinaryQuantumSoul** [comment]
Are you sure you enabled the plugin in better discord plugin list ? And is the color code inside a code block?

**Comment by FenekkuKitsune** [comment]
Ah, I wasn't aware the color code needed to be in a code block. That's not stated on the plugin description or anywhere.

**Comment by BinaryQuantumSoul** [comment]
You can also use an inline block. Anyway does it work now ?

**Comment by FenekkuKitsune** [comment]
Yes.
